name: Deployment Client - Development

on:
  push:
    branches:
      - develop
      - feature/revamp

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group:
    '${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Next.js project
        run: bun run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./develop/
